import { vars } from "nativewind"
import theme from "@budio/theme-config/theme"

export const colors = {
  light: {
    background: theme.lightBackground,
    primary: theme.lightPrimary,
    foreground: theme.lightForeground,
    card: theme.lightCard,
    cardForeground: theme.lightCardForeground,
    popover: theme.lightPopover,
    popoverForeground: theme.lightPopoverForeground,
    primaryForeground: theme.lightPrimaryForeground,
    secondary: theme.lightSecondary,
    secondaryForeground: theme.lightSecondaryForeground,
    muted: theme.lightMuted,
    mutedForeground: theme.lightMutedForeground,
    accent: theme.lightAccent,
    accentForeground: theme.lightAccentForeground,
    destructive: theme.lightDestructive,
    destructiveForeground: theme.lightDestructiveForeground,
    border: theme.lightBorder,
  },
  dark: {
    background: theme.darkBackground,
    primary: theme.darkPrimary,
    foreground: theme.darkForeground,
    card: theme.darkCard,
    cardForeground: theme.darkCardForeground,
    popover: theme.darkPopover,
    popoverForeground: theme.darkPopoverForeground,
    primaryForeground: theme.darkPrimaryForeground,
    secondary: theme.darkSecondary,
    secondaryForeground: theme.darkSecondaryForeground,
    muted: theme.darkMuted,
    mutedForeground: theme.darkMutedForeground,
    accent: theme.darkAccent,
    accentForeground: theme.darkAccentForeground,
    destructive: theme.darkDestructive,
    destructiveForeground: theme.darkDestructiveForeground,
    border: theme.darkBorder,
  },
}

export const themes = {
  light: vars({
    "--background": theme.lightBackground,
    "--primary": theme.lightPrimary,
    "--foreground": theme.lightForeground,
    "--card": theme.lightCard,
    "--card-foreground": theme.lightCardForeground,
    "--popover": theme.lightPopover,
    "--popover-foreground": theme.lightPopoverForeground,
    "--primary-foreground": theme.lightPrimaryForeground,
    "--secondary": theme.lightSecondary,
    "--secondary-foreground": theme.lightSecondaryForeground,
    "--muted": theme.lightMuted,
    "--muted-foreground": theme.lightMutedForeground,
    "--accent": theme.lightAccent,
    "--accent-foreground": theme.lightAccentForeground,
    "--destructive": theme.lightDestructive,
    "--destructive-foreground": theme.lightDestructiveForeground,
    "--border": theme.lightBorder,
  }),
  dark: vars({
    "--background": theme.darkBackground,
    "--primary": theme.darkPrimary,
    "--foreground": theme.darkForeground,
    "--card": theme.darkCard,
    "--card-foreground": theme.darkCardForeground,
    "--popover": theme.darkPopover,
    "--popover-foreground": theme.darkPopoverForeground,
    "--primary-foreground": theme.darkPrimaryForeground,
    "--secondary": theme.darkSecondary,
    "--secondary-foreground": theme.darkSecondaryForeground,
    "--muted": theme.darkMuted,
    "--muted-foreground": theme.darkMutedForeground,
    "--accent": theme.darkAccent,
    "--accent-foreground": theme.darkAccentForeground,
    "--destructive": theme.darkDestructive,
    "--destructive-foreground": theme.darkDestructiveForeground,
    "--border": theme.darkBorder,
  }),
}
